apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: slackernews
spec:
  collectors:
    - http:
        collectorName: slack
        get:
          url: https://api.slack.com/methods/api.test
    - postgres:
        collectorName: postgres
        uri: 'postgresql://slackernews:password@localhost:5432/slackernews?sslmode=require'

  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.20.0"
              message: SlackerNews requires Kubernetes 1.20.0 or later
          - pass:
              message: The version of Kubernetes is compatible with SlackerNews
    - textAnalyze:
        checkName: slack
        fileName: slack.json
        regex: '"status": 200,'
        outcomes:
          - pass:
              when: "true"
              message: "Can access the Slack API"
          - fail:
              when: "false"
              message: "Cannot access the Slack API. Check that the server can reach the internet and check [status.slack.com](https://status.slack.com)."
