apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: slackernews
spec:
  collectors:
    - http:
        collectorName: slack
        get:
          url: https://api.slack.com/methods/api.test
    - postgres:
        collectorName: postgres
        uri: 'postgresql://slackernews:password@localhost:5432/slackernews?sslmode=require'

  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.20.0"
              message: SlackerNews requires Kubernetes 1.20.0 or later
          - pass:
              message: The version of Kubernetes is compatible with SlackerNews
    - distribution:
        outcomes:
          - pass:
              when: "== kurl"
              message: kurl is a supported platform
          - pass:
              when: "== gke"
              message: GKE is a supported platform
          - pass:
              when: "== aks"
              message: AKS is a supported platform
          - pass:
              when: "== eks"
              message: EKS is a supported platform
          - pass:
              when: "== k3s"
              message: K3s is a supported platform
          - warn:
              when: "== docker-desktop"
              message: This application has not been tested on Docker Desktop
          - warn:
              message: This Kubernetes platform is not regularly tested, but there are no known compatibility issues.
    - textAnalyze:
        checkName: slack
        fileName: slack.json
        regex: '"status": 200,'
        outcomes:
          - pass:
              when: "true"
              message: "Can access the Slack API"
          - fail:
              when: "false"
              message: "Cannot access the Slack API. Check that the server can reach the internet and check [status.slack.com](https://status.slack.com)."
