apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: slackernews
spec:
  title: SlackerNews
  icon: "https://uploads-ssl.webflow.com/6310ad0e6a18aa1620da6ae8/6330e04f42bc6a7ba03b4725_snicon.png"
  requireMinimalRBACPrivileges: true
  allowRollback: true
  minKotsVersion: 1.79.0
  ports:
    - serviceName: slackernews
      servicePort: 3000
      localPort: 3000
      applicationUrl: "http://slackernews"
  statusInformers:
    - deployment/slackernews
    - '{{repl if ConfigOptionEquals "deploy_postgres" "1"}}statefulset/postgres{{repl end}}'
    - deployment/slackernews-nginx
  graphs:
    - title: DAU
      query: 'sum(user_signup_events_total)'
images:
  slackernews:
    pullSecret: repl{{ ImagePullSecretName }}
    repository: ghcr.io/slackernews/slackernews-web
