apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: slackernews
spec:
  title: SlackerNews
  icon: "https://uploads-ssl.webflow.com/6310ad0e6a18aa1620da6ae8/6330e04f42bc6a7ba03b4725_snicon.png"
  requireMinimalRBACPrivileges: true
  allowRollback: true
  minKotsVersion: 1.79.0
  ports:
    - serviceName: web
      servicePort: 80
      localPort: 80
      applicationUrl: "http://slackernews-nginx"
  statusInformers:
    - deployment/slackernews-frontend
  graphs:
    - title: DAU
      query: 'sum(user_signup_events_total)'
images:
  slackernews_api:
    pullSecret: repl{{ ImagePullSecretName }}
    repository: ghcr.io/slackernews/slackernews-api
  slackernews_migrations:
    pullSecret: repl{{ ImagePullSecretName }}
    repository: ghcr.io/slackernews/slackernews-migrations
  slackernews:
    pullSecret: repl{{ ImagePullSecretName }}
    repository: ghcr.io/slackernews/slackernews-web
