apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: slackernews
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: slackernews
    chartVersion: $VERSION

  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values:
    postgres:
      enabled: repl{{ ConfigOption "deploy_postgres" | ParseBool }}
      deploy_postgres: repl{{ ConfigOption "deploy_postgres" | ParseBool }}
      password: repl{{ ConfigOption "postgres_password"}}
      uri: repl{{ ConfigOption "postgres_external_uri" }}
    slack:
      botToken: repl{{ ConfigOption "slack_bot_token" }}
      userToken: repl{{ ConfigOption "slack_user_token" }}
      clientId: repl{{ ConfigOption "slack_clientid" }}
      clientSecret: repl{{ ConfigOption "slack_clientsecret" }}
    slackernews:
      domain: repl{{ ConfigOption "slackernews_domain" }}
    admin-console:
      enabled: false
    replicated:
      enabled: false
      preflights: false
    nginx:
      enabled: repl{{ ConfigOption "nginx_enabled" | ParseBool }}
      service:
        type: repl{{ ConfigOption "nginx_service_type" }}
        nodePort:
          port: repl{{ ConfigOption "nginx_node_port_port" }}
    service:
      type: repl{{ ConfigOption "slackernews_service_type" }}
      nodePort:
        port: repl{{ ConfigOption "slackernews_node_port_port" }}
      tls:
        enabled: true
        cert: |
          repl{{ ConfigOption "tls_cert" | nindent 10 }}
        key: |
          repl{{ ConfigOption "tls_key" | nindent 10 }}
    images:
      pullSecrets:
        replicated:
          dockerconfigjson: ""
      slackernews:
        pullSecret: repl{{ ImagePullSecretName }}
        repository: repl{{ LocalImageName "$REGISTRY/$IMAGE" }}
  # builder values provide a way to render the chart with all images
  # and manifests. this is used in replicated to create airgap packages
  builder:
    postgres:
      password: repl{{ ConfigOption "postgres_password"}}
    admin-console:
      enabled: false
