postgres:
  enabled: false
  deploy_postgres: false
  password: ""
  uri: ""
  existingSecretName: ""
  existingSecretPasswordKey: ""
  existingSecretUriKey: ""
  service:
    type: ClusterIP
    nodePort:
      port:

sqlite:
  enabled: true

ingress:
  annotations: {}
  enabled: false
  ingressClassName: ""
nginx:
  service:
    type: ClusterIP
    nodePort:
      port:

service:
  tls:
    enabled: false
    existingSecretName: ""
    existingSecretCertKey: ""
    existingSecretKeyKey: ""
    cert: ""
    key: ""

slack:
  botToken: ""
  userToken: ""
  clientId: ""
  clientSecret: ""
  existingSecretName: ""
  existingSecretBotTokenKey: ""
  existingSecretUserTokenKey: ""
  existingSecretClientIdKey: ""
  existingSecretClientSecretKey: ""

slackernews:
  domain: ""
  # set default admin users
  adminUserEmails: ""
  # display running version on admin dashboard
  version: "$TAG"

images:
  pullSecrets:
    replicated:
      name: proxypullsecret
  nginx:
    repository: $REGISTRY/$NGINX_IMAGE
    pullPolicy: IfNotPresent
  slackernews:
    repository: "$REGISTRY/$IMAGE:$TAG"
    pullPolicy: IfNotPresent
