{{ if ne .Values.replicated.preflights false }}
apiVersion: v1
kind: Secret
metadata:
  name: slackernews-preflight-mypreflight
  labels:
    troubleshoot.io/kind: preflight
stringData: 
  preflight.yaml: |- 
    apiVersion: troubleshoot.sh/v1beta2
    kind: Preflight
    metadata:
      name: slackernews-preflight-mypreflight
    spec:
      collectors:      
        - data:
            name: example.json
            data: |
              {
                "foo": "bar",
                "stuff": {
                  "foo": "bar",
                  "bar": true
                },
                "morestuff": [
                  {
                    "foo": {
                      "bar": 123
                    }
                  }
                ]
              }
      analyzers:
        - jsonCompare:
            checkName: Compare JSON Example
            fileName: example.json
            path: "morestuff.[0].foo.bar"
            value: |
              123
            outcomes:
              - fail:
                  when: "false"
                  message: The collected data does not match the value.
              - pass:
                  when: "true"
                  message: The collected data matches the value.

{{ end }}